version: '3.8'

services:
  users-service:
    image: microseversk/scam-bank-users-service:latest
    container_name: users-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    restart: unless-stopped
