services:
  scam-bank-users-service:
    image: microseversk/scam-bank-users-service:latest
    build: .
    container_name: scam-bank-users-service
    restart: always
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DB_URL=postgresql://nest:nest@postgres:5432/users
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=nest
      - DB_PASS=nest
      - DB_NAME=users
      - PORT=3001
    ports:
      - '3001:3001'

  postgres:
    image: postgres:15
    container_name: postgres-users
    restart: always
    environment:
      - POSTGRES_USER=nest
      - POSTGRES_PASSWORD=nest
      - POSTGRES_DB=users
    volumes:
      - postgres_users:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_users:
